name: SourceSDK.ENV.Editor - develop

on:
  push:
    branches: [ develop ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: windows-latest
  
    steps:

    - name: Set the value
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@master
      with:
        clean: true
        fetch-depth: 0
        lfs: true
        submodules: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with: 
        vs-prerelease: true
        msbuild-architecture: x86

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Add nuget private repo
      run: nuget add source --username  ${{ secrets.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/colhountech/index.json"

    - name: Restore NuGet Packages
      run: nuget restore src/SourceSDK.ENV.Editor.sln
 
    - name: Build Debug
      run: msbuild src/SourceSDK.ENV.Editor.sln /p:Configuration=Debug
